{% set name = "captum" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/captum-{{ version }}.tar.gz
  sha256: 7ca87d0dc67b3b7589a730b970b9536172a5468e0e31bf8657fdd73abc568a33

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pytorch >=1.6
    - tqdm

test:
  imports:
    - captum
    - captum._utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://captum.ai
  summary: Model interpretability for PyTorch
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Captum is a model interpretability and understanding library for PyTorch.
    Captum means comprehension in Latin and contains general purpose
    implementations of integrated gradients, saliency maps, smoothgrad,
    vargrad and others for PyTorch models. It has quick integration for models
    built with domain-specific libraries such as torchvision, torchtext, and others.

    *Captum is currently in beta and under active development!*

    PyPI: [https://pypi.org/project/captum/](https://pypi.org/project/captum/)

  doc_url: https://captum.ai/
  dev_url: https://github.com/pytorch/captum

extra:
  recipe-maintainers:
    - sugatoray
    # Maintainers from package repo
    - NarineK
    - aobo-y
    - vivekmig
