{% set name = "captum" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73f2e5a07ffe6ac6647a6f12cd2f67f0d8f717329f150ddf08ef73cba0858d26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - numpy <2.0
    - packaging
    - python >={{ python_min }}
    - pytorch >=1.10
    - tqdm

test:
  imports:
    - captum
    - captum._utils
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://captum.ai/
  summary: 'Model interpretability for PyTorch'
  description: |
    Captum is a model interpretability and understanding library for PyTorch.
    Captum means comprehension in Latin and contains general purpose implementations
    of integrated gradients, saliency maps, smoothgrad, vargrad and others for
    PyTorch models. It has quick integration for models built with domain-specific
    libraries such as torchvision, torchtext, and others.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://captum.ai/
  dev_url: https://github.com/pytorch/captum

extra:
  recipe-maintainers:
    - sugatoray
    # Maintainers from package repo
    - NarineK
    - aobo-y
    - vivekmig
