{% set name = "captum" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/captum-{{ version }}.tar.gz
  sha256: 84af2c8793d34c440a351793b5ca705b8542745e2dc8bc24afb1d9b86f3bf6ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - pytorch >=1.6

test:
  imports:
    - captum
    - captum._utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://captum.ai
  summary: Model interpretability for PyTorch
  dev_url: https://github.com/pytorch/captum
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Captum is a model interpretability and understanding library for PyTorch.
    Captum means comprehension in Latin and contains general purpose
    implementations of integrated gradients, saliency maps, smoothgrad,
    vargrad and others for PyTorch models. It has quick integration for models
    built with domain-specific libraries such as torchvision, torchtext, and others.

    *Captum is currently in beta and under active development!*

    PyPI: [https://pypi.org/project/captum/](https://pypi.org/project/captum/)

  doc_url: https://captum.ai/
  dev_url: https://github.com/pytorch/captum

extra:
  recipe-maintainers:
    - sugatoray
    # Maintainers from package repo
    - NarineK
    - aobo-y
    - vivekmig
